repos:

  - repo: https://github.com/rtts/djhtml
    rev: main
    hooks:
      - id: djhtml

  - repo: https://github.com/myint/autoflake
    rev: master
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports']

  - repo: https://github.com/pycqa/isort
    rev: main
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8

  - repo: https://github.com/psf/black
    rev: main
    hooks:
      - id: black
