repos:

  - repo: https://github.com/rtts/djhtml
    rev: v1.4.9
    hooks:
      - id: djhtml

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports']

  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
