# Generated by Django 3.0.3 on 2020-03-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_initial_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='polymorphic_ctype',
        ),
    ]
